<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260128110744 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, command VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, service_id INT NOT NULL, incident_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_47CC8C92ED5CA9E6 ON action (service_id)');
        $this->addSql('CREATE INDEX IDX_47CC8C9259E53FB9 ON action (incident_id)');
        $this->addSql('CREATE TABLE incident (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, severity VARCHAR(10) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, summary TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE incident_service (incident_id INT NOT NULL, service_id INT NOT NULL, PRIMARY KEY (incident_id, service_id))');
        $this->addSql('CREATE INDEX IDX_4657800F59E53FB9 ON incident_service (incident_id)');
        $this->addSql('CREATE INDEX IDX_4657800FED5CA9E6 ON incident_service (service_id)');
        $this->addSql('CREATE TABLE journal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, message TEXT NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, incident_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1A7E74D59E53FB9 ON journal (incident_id)');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, criticality VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C92ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C9259E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_service ADD CONSTRAINT FK_4657800F59E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_service ADD CONSTRAINT FK_4657800FED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74D59E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C92ED5CA9E6');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C9259E53FB9');
        $this->addSql('ALTER TABLE incident_service DROP CONSTRAINT FK_4657800F59E53FB9');
        $this->addSql('ALTER TABLE incident_service DROP CONSTRAINT FK_4657800FED5CA9E6');
        $this->addSql('ALTER TABLE journal DROP CONSTRAINT FK_C1A7E74D59E53FB9');
        $this->addSql('DROP TABLE action');
        $this->addSql('DROP TABLE incident');
        $this->addSql('DROP TABLE incident_service');
        $this->addSql('DROP TABLE journal');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
